"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Content Security Policy (CSP) - Basic implementation
# For full CSP, install django-csp: pip install django-csp
# and add 'csp.middleware.CSPMiddleware' to MIDDLEWARE

# Manual CSP headers can be added in a custom middleware
# This is a basic implementation - consider using django-csp for production


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your-secret-key-here'  # Replace with actual secret key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Set to False for production

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'yourdomain.com']  # Add your production domain

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# SECURITY SETTINGS CONFIGURATION
# These settings enhance application security by enabling various protections

# HTTPS CONFIGURATION - Step 1: Configure Django for HTTPS Support

# Redirect all non-HTTPS requests to HTTPS
# SECURITY: Ensures all traffic uses encrypted HTTPS connections
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS) settings
# SECURITY: Instructs browsers to only access the site via HTTPS for the specified time
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds

# SECURITY: Include all subdomains in the HSTS policy
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURITY: Allow preloading of HSTS policy in browser preload lists
SECURE_HSTS_PRELOAD = True

# SECURITY: Configure proxy SSL header for detecting HTTPS behind proxy
# This tells Django to look for the X-Forwarded-Proto header to detect HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Step 2: Enforce Secure Cookies

# SECURITY: Ensure session cookies are only transmitted over HTTPS
SESSION_COOKIE_SECURE = True

# SECURITY: Ensure CSRF cookies are only transmitted over HTTPS
CSRF_COOKIE_SECURE = True

# Step 3: Implement Secure Headers

# SECURITY: Prevent XSS attacks by enabling browser's XSS filtering
SECURE_BROWSER_XSS_FILTER = True

# SECURITY: Prevent clickjacking by denying framing of the site
X_FRAME_OPTIONS = 'DENY'

# SECURITY: Prevent MIME type sniffing which could lead to XSS
SECURE_CONTENT_TYPE_NOSNIFF = True

# Additional security headers
# SECURITY: Set Referrer Policy to enhance privacy and security
SECURE_REFERRER_POLICY = 'same-origin'


# DEPLOYMENT CONFIGURATION FOR HTTPS
#
# For production deployment with HTTPS, you need to configure your web server
# to handle SSL/TLS certificates. Below are examples for common web servers:
#
# IMPORTANT: When using a reverse proxy (like Nginx or Apache), ensure they set
# the X-Forwarded-Proto header so Django can properly detect HTTPS connections.
#
# NGINX Configuration Example:
#
# server {
#     listen 443 ssl http2;
#     server_name yourdomain.com;
#
#     ssl_certificate /path/to/your/certificate.crt;
#     ssl_certificate_key /path/to/your/private.key;
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512;
#
#     location / {
#         proxy_pass http://127.0.0.1:8000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;  # IMPORTANT: This tells Django it's HTTPS
#     }
# }
#
# server {
#     listen 80;
#     server_name yourdomain.com;
#     return 301 https://$server_name$request_uri;
# }
#
# Apache Configuration Example:
#
# <VirtualHost *:443>
#     ServerName yourdomain.com
#     SSLEngine on
#     SSLCertificateFile /path/to/your/certificate.crt
#     SSLCertificateKeyFile /path/to/your/private.key
#
#     ProxyPreserveHost On
#     ProxyPass / http://127.0.0.1:8000/
#     ProxyPassReverse / http://127.0.0.1:8000/
#     RequestHeader set X-Forwarded-Proto "https"  # IMPORTANT: This tells Django it's HTTPS
# </VirtualHost>
#
# <VirtualHost *:80>
#     ServerName yourdomain.com
#     Redirect permanent / https://yourdomain.com/
# </VirtualHost>
